name: CI/CD Pipeline - rsync

on:
  push:
    branches-ignore:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Verify pnpm installation
      - name: Verify pnpm
        run: pnpm --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run Prettier
      - name: Run Prettier
        run: pnpm prettier --check .

      # Step 6: Run ESLint
      - name: Run ESLint
        run: pnpm eslint .

      # Step 7: Run Jest tests
      - name: Run Jest tests
        run: pnpm test

  build-and-deploy:
    runs-on: ubuntu-24.04
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Verify pnpm installation
      - name: Verify pnpm
        run: pnpm --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Step 5: Build the app
      - name: Build the app
        run: |
          # rm -rf out  # Ensure no stale builds
          pnpm build
          echo "Build output contents:"
          ls -la out || echo "out/ directory not created"

      # Step 6: Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh-keyscan -H ${HOST} >> ~/.ssh/known_hosts
        env:
          HOST: ${{ secrets.SSH_HOST }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 7: Deploy with rsync
      - name: Deploy to VPS
        if: github.ref == 'refs/heads/main' # Only deploy from main branch
        run: |
          rsync -avz --delete -e "ssh -i ssh_key" out/ ${USER}@${HOST}:/var/www/dashboard/
          ssh -i ssh_key ${USER}@${HOST} "ls -la /var/www/dashboard/; grep -R 'Asgard' /var/www/dashboard/ || echo 'Keyword not found in deployed files'"
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
